### ISSUE TITLE
Categories returning wrong number of players

### ISSUE THREAD

**Issue by shortymike123** [speedruncomorg/api#49]
I may be misunderstanding its function, but from what I can understand from the documentation, when checking the "players" section of the API, the value should be the number of the players (i.e if there are 6 runs for a category, the "exactly" value should be 6).

Exact wording from the documentation: `players is the number of participants for runs in this category. At the moment, there are two possible type values: exactly and up-to, which should be self-explanatory.`

This however does not seem to be the case, example:
From this  [(http://www.speedrun.com/api/v1/categories/p7kjqnd3)](http://www.speedrun.com/api/v1/categories/p7kjqnd3) call I get `"players":{"type":"exactly","value":1}`

Where as from the leaderboard [http://www.speedrun.com/crash1#100](http://www.speedrun.com/crash1#100) that does not seem to be correct (expecting the value of 58).

Is this a bug, or is this me misunderstanding the documentation? If this is a misunderstanding, could the readme be adjusted to better clarify the use of "players"?

**Comment by Lighnat0r** [comment]
Rather than the total number of players that has a run in the category, 'players' is the number of players per run (i.e. 1 for single player runs, 2 or more for coop runs).

For example, the coop category of Portal 2 will return ``players: {
type: "exactly",
value: 2
}``
Since each run in that category is done by 2 players:
http://www.speedrun.com/api/v1/categories/l9kv40kg
https://www.speedrun.com/Portal_2#Cooperative_Game

I'll edit the wording in the documentation to make it more clear there as well.
